version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  plot_hist:
    run: r:latest analysis/age_hist.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: output/age_hist_log.txt
        figure: output/age_hist.png
   

